version: "3.7"
x-common-variables: &common-variables
  NODE_ENV: local
  AWS_ACCESS_KEY_ID: na
  AWS_SECRET_ACCESS_KEY: na
  AWS_REGION: us-east-2
services:
  localstack:
    image: localstack/localstack
    container_name: productservice-aws_emulator
    environment: 
      - SERVICES=sqs,dynamodb
    ports:
      - 4566:4566
      - 8000:8000
      - 4569:4569
  init:
    image: mesosphere/aws-cli
    container_name: productservice-init_aws_emulator
    volumes:
      - ./init:/project
    environment:
      AWS_ACCESS_KEY_ID: anykey
      AWS_SECRET_ACCESS_KEY: anysecret
      AWS_DEFAULT_REGION: us-east-2
    depends_on:
      - localstack
    entrypoint:
      - /bin/sh
      - /project/init.sh
networks: 
  default:
    name: productservice-network